/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.MedicalRecord;

/**
 *
 * @author zzz
 */
public class ViewMedicalRecord extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedicalRecord
     */
    public ViewMedicalRecord(MedicalRecord medicalRecord) {
        initComponents();
        txt_MedicalRecordNumber.setText(medicalRecord.getMedicakRecordNumber());
        txt_Alergy1.setText(medicalRecord.getAlergy1());
        txt_Alergy2.setText(medicalRecord.getAlergy2());
        txt_Alergy3.setText(medicalRecord.getAlergy3());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Alergy3 = new javax.swing.JTextField();
        txt_Alergy1 = new javax.swing.JTextField();
        lb_StreetAddress = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MedicalRecordNumber = new javax.swing.JTextField();
        txt_Alergy2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        txt_Alergy3.setEditable(false);

        txt_Alergy1.setEditable(false);

        lb_StreetAddress.setText("MedicalRecordNumber");

        jLabel2.setText("Alergy1");

        jLabel3.setText("Alergy2");

        jLabel4.setText("Alergy3");

        txt_MedicalRecordNumber.setEditable(false);
        txt_MedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MedicalRecordNumberActionPerformed(evt);
            }
        });

        txt_Alergy2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(lb_StreetAddress))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MedicalRecordNumber)
                    .addComponent(txt_Alergy3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txt_Alergy2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txt_Alergy1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_StreetAddress)
                    .addComponent(txt_MedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MedicalRecordNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_StreetAddress;
    private javax.swing.JTextField txt_Alergy1;
    private javax.swing.JTextField txt_Alergy2;
    private javax.swing.JTextField txt_Alergy3;
    private javax.swing.JTextField txt_MedicalRecordNumber;
    // End of variables declaration//GEN-END:variables
}
